export const siteConfig = {
  name: 'ToolPilot AI',
  tagline: 'Discover the right AI tools. Create more. Work smarter.',
  description: 'Discover and compare useful AI tools for creators, students, developers and businesses.',
  domain: import.meta.env.VITE_SITE_URL || 'https://toolpilot.ai',
  siteUrl: import.meta.env.VITE_SITE_URL || 'https://toolpilot.ai',
  gaMeasurementId: import.meta.env.VITE_GA_MEASUREMENT_ID || '',
  adsenseClient: import.meta.env.VITE_ADSENSE_CLIENT || '',
  adsEnabled: import.meta.env.VITE_ADS_ENABLED === 'true',
  contactEndpoint: import.meta.env.VITE_CONTACT_ENDPOINT || '',
  newsletterEndpoint: import.meta.env.VITE_NEWSLETTER_ENDPOINT || '',
  author: {
    name: 'ToolPilot AI Editorial',
    slug: 'toolpilot-ai-editorial',
    bio: 'ToolPilot AI Editorial develops practical, source-aware guides for evaluating AI tools and improving everyday workflows.',
    areas: ['AI tools', 'workflow guidance', 'product research', 'editorial quality'],
  },
};

export const publicRoutes = [
  '/',
  '/ai-tools',
  '/ai-video',
  '/ai-image',
  '/ai-writing',
  '/ai-audio',
  '/ai-coding',
  '/ai-creators',
  '/ai-business',
  '/ai-students',
  '/comparisons',
  '/search',
  '/about',
  '/contact',
  '/privacy-policy',
  '/terms',
  '/disclaimer',
  '/affiliate-disclosure',
  '/editorial-policy',
  '/404',
  '/articles/:slug',
  '/tools/:slug',
  '/compare/:slug',
  '/authors/:slug',
];
